# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    base_path: "ckeditor"
    js_path:   "ckeditor/ckeditor.js"

ckfinder:
    connector:
        licenseName: "moldwebs"
        licenseKey: "*W?Y-*1**-9**E-*A**-*B**-V*X*-6**9"
        authenticationClass: App\Auth\CustomCKFinderAuth
