version: '2'

services:

  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www/html
      - ./docker/php/default.ini:/usr/local/etc/php/conf.d/default.ini

  nginx:
    image: nginx:1.13.8
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    environment:
      - INDEX_LOCATION=/public

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    depends_on:
      - php-fpm
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  nodejs:
    build:
      context: ./docker/nodejs
    ports:
      - 30001:3000
    volumes:
      - ./socket:/usr/src/app
    depends_on:
      - rabbitmq
    environment:
      AMQP_URL: ${AMQP_URL}

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 8071:15672
      - 5672:5672
    volumes:
      - ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins