controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

backend:
    resource: ../../src/Controller/Backend/
    type: annotation
    prefix: admin