#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

sg_datatables_bundle:
  resource: "@SgDatatablesBundle/Controller/"
  type:     annotation
  prefix:   /sg

ckfinder_connector:
  resource: "@CKSourceCKFinderBundle/Resources/config/routing.yml"
  prefix:   /

api:
  prefix: /api
  resource: '../src/Controller/Api'